linters:
  disable:
    # deprecated
    - tenv

    # obnoxious
    - cyclop
    - depguard
    - dupl
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - godox
    - lll
    - mnd
    - nlreturn
    - paralleltest
    - testpackage
    - wsl
    - varnamelen
  enable-all: true

linters-settings:
  forbidigo:
    forbid:
      - '^errors\.Wrap$'
      - '^errors\.Wrapf$'
      - '^fmt\.Errorf$'
  gci:
    sections:
      - Standard
      - Default
      - Prefix(github.com/brandur)

  gocritic:
    disabled-checks:
      - commentFormatting

  gosec:
    excludes:
      - G203

  wrapcheck:
    ignorePackageGlobs:
      - github.com/brandur/*
