linters:
  disable:
    # obnoxious
    - cyclop
    - dupl
    - exhaustruct
    - exhaustivestruct
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gochecknoglobals
    - gocognit
    - gocyclo
    - godox
    - gomnd
    - nlreturn
    - paralleltest
    - testpackage
    - wsl
    - varnamelen

    # buggy
    - execinquery

    # deprecated
    - golint
    - interfacer
    - maligned
    - scopelint
  enable-all: true

linters-settings:
  forbidigo:
    forbid:
      - '^errors\.Wrap$'
      - '^errors\.Wrapf$'
      - '^fmt\.Errorf$'
  gci:
    sections:
      - Standard
      - Default
      - Prefix(github.com/brandur)

  gocritic:
    disabled-checks:
      - commentFormatting

  gosec:
    excludes:
      - G203

  wrapcheck:
    ignorePackageGlobs:
      - github.com/brandur/*
