#
# Page metadata
#
# Contains metadata for pages like their titles and any extra CSS classes that
# they should belong to.
#

about:
  title: About

accidental:
  title: Accidental
  body_class: quote

crying:
  title: Crying
  body_class: quote

favors:
  title: Favors
  body_class: quote

lies:
  title: Lies
  body_class: quote

now:
  title: What I'm Doing Now

talks:
  title: Talks

that-sunny-dome:
  title: That Sunny Dome
  body_class: quote
